# Generated by Django 4.1.1 on 2022-09-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=100)),
                ('vencimiento_producto', models.DateTimeField()),
                ('descripcion_producto', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
